apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
  - name: app-container
    image: busybox
    command: ["sleep", "3600"]
    envFrom:
    - secretRef:
        name: my-secret
