apiVersion: v1
kind: Pod
metadata:
  name: readiness-demo
spec:
  containers:
  - name: demo
    image: europe-west3-docker.pkg.dev/prometheus-devops-course/gcr-docker-demo/demo:v1.0.0
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
