apiVersion: v1
kind: Pod
metadata:
  name: volume-mounts-demo
spec:
  containers:
  - name: app-container
    image: nginx
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html-volume
    hostPath:
      path: /data/html
