apiVersion: v1
kind: Pod
metadata:
  name: volume-mounts-demo
spec:
  containers:
  - name: app-container
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Hello, World!' > /usr/share/hello/index.html && sleep 3600"]
    volumeMounts:
    - name: data-volume
      mountPath: /usr/share/hello
  volumes:
  - name: data-volume
    emptyDir: {}
